server:
  port: 8080
  servlet:
    context-path: /api # Context path of the application.

logging:
  level: # Log levels severity mapping. For instance, `logging.level.org.springframework=DEBUG`.
    org.springframework.web: debug
    org.springframework.web.filter: debug

app:
  filter:
    trace-id:
      enabled: true
      exclude-patterns:
        - /health-check
    request-logging:
      enabled: true
      include-query-string: true
      include-client-info: true
      include-headers: true
      include-payload: true
      exclude-patterns:
        - /health-check
